### ISSUE TITLE
Websocket JSON (Callback for ALL symbols data on one exchange)

### ISSUE THREAD

**Issue by Paul-Thompson54** [Coinigy/bittrex-websocket-feed#1]
I understand how to call for data from one market on one exchange but how would I go about requesting all markets on one exchange data. I have read about "TICKER" to request all favourited markets but For this i'm not sure the code to enter my private Id code.

Thanks for any help in advance.
`var scChannel = SCsocket.subscribe("WSTRADE-BTRX--BTC--USDT");`

**Comment by ByronAP** [comment]
"all markets on one exchange data" you can't. You can get your top 20 favorites by subscribing to your private channel, you can get your private channel id from your coinigy account settings->my account->coingiy api->Click to reveal my Private Channel ID (Websocket API) then subscribe to it SCsocket.subscribe("my-private-channel-id")

**Comment by Paul-Thompson54** [comment]
Cheers Byron, over to Bittrex web socket I go.
